name: Deploy App
on:
  pull_request:
    types:
      - opened
    branches:
      - 'main'
      - 'development-*' # dev-new dev-this-is-new
      - 'feature/**' # feature/new-feature/new/button
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'development-*' #development-new-branch-name
      - 'feature/**' # feature/new-feature/button
    # paths-ignore:
    #   - '.github/workflows/*'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name:  Install NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deeps-node-modules-${{ hashFiles('**/package-lock.json') }}      
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name:  Install NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deeps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name:  Install NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deeps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Publish JS filename
        id: publish
        run: find dist/homepage/*.js -type f -execdir echo '::set-output name=script-file::{}' ';'
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
          # path: |
          #   dist
          #   package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: Output contents
        run: ls
      - name: Output filename
        run: echo "${{ needs.build.outputs.script-file }}"
      - name: Deploy
        run : echo "Deploying ..."